#!/bin/bash
sudo aptitude install -y python2.7-dev
virtualenv --no-site-packages env
# get requirements from YG cheeseshop
DISTUTILS_DIR=`env/bin/python -c "import distutils, os; print(os.path.dirname(distutils.__file__))"`
echo "[easy_install]
allow_hosts=*.polimetrix.com,*.yougov.net
find_links=http://cheeseshop.polimetrix.com
index_url=http://cheese.yougov.net
" > $DISTUTILS_DIR/distutils.cfg
env/bin/python setup.py sdist
env/bin/easy_install -f dist airportlocker[server]
env/bin/python runtest.py --ignore env --junitxml=test_results.xml
sudo aptitude remove -y python2.7-dev
