#!/bin/bash
python2.7 -c "import setuptools; setuptools.setup()" setopt -c easy_install -o index-url -s http://cheese.yougov.net
python2.7 setup.py ptr --extras --index-url=http://cheese.yougov.net --addopts='--junitxml="test results.xml"'
