production : False
# Integration only zencoder api key. You'll need a production one for long videos.
zencoder_api_key: 06f15509882cc8afb0565af79a9206e1
zencoder_outputs:
- {label: HTML5/Flash/MP4/H.264, h264_profile: high, extension: mp4, suffix: html5_mp4}
- {label: HTML5/WebM, extension: webm, suffix: html5_webm}
- {label: HTML5/Ogg, extension: ogg, suffix: html5_ogg}
- {label: Mobile/3GP/MPEG4 non-smartphones, size: 320x240, extension: 3gp, suffix: mov_3gp}
aws_s3_bucket: yg-zencoder-test
aws_accesskey: AKIAIZBD3TBZU4GRD23A
aws_secretkey: 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
aws_keypairid: APKAJ3GWQDXPR6IULVXA
aws_privatekey: "\n-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQDVQoWIfB54Mac1X8Ia+qOilCs1OdhdoL3Be+ZwekRiQCF63bWU\n9aBaQK120IIbEUa6PN1BL+4KVQKdpSES06DYGxH9eLX/ypXFQysNFqyrnSRVs41a\nwiuqFOHgQCv5AJOGuy71caf7aNMHz77srnggjciI2LI92DdpNrxI42RSnQIDAQAB\nAoGARPMmA1PF8ixzmFEmi9x/bYAkXCggqVzgHR93COSvGWkMqhHmtIuZ1bRVoTWW\n6zNxv6MQEhRyDQshNmD+SXz84mqmiVBrKqELmiJfVjsBxbm8P6v2gSLYbTMbw9T/\nJRWDtHXUjgvSMHE2pN6DIup5bICNaLDXNa1yZk+csCagkYECQQD6BQpGN6sBmOe2\nAuxSAQlt53T5GBsXfG5Zri+aeSp1Vs7mQnra5O7p1OH44iJrjGnx0zHQss5qw12y\nQ9VyXUf9AkEA2lxjSsvPkbwzqIQlt7TqYP2gAQBL10V7Nt78VIWC6pOlgmSoTTrG\nkvysPy0XnQjLWpXLbHiDH/v3rdm5UYinIQJBAO/0tGat+OcgjIqohY0yx4z+zspf\nc2j4GKTjw3Zbgf96IDroZSb+/7nWgkavKl/UNL5OdwoZAnl/Jcb4ybvogTUCQCHh\nvgJoF4AcfMOEJboYl1mPYRlmq13uyQydkvemc8bkPAU8iyTYnuFF1ZBD9esG507Z\n+WOOW4JF/Yt7QhcVpiECQQCr4H9AgqgbrA31i6yy5x/49Y7Lde4EDXJxB6cNOFg0\nhq/tCtKMolReqp1TCD06yzB3lwznkJOe33b9pTAnffxL\n-----END RSA PRIVATE KEY-----\n"
aws_signature_ttl: 600
zencoder_notification_url: http://localhost:5600/_zencoder/
public_url: http://localhost:5600/
